### ISSUE TITLE
Sobre la detección de algunos obstáculos...

### ISSUE THREAD

**Issue by Autinfit** [Autinfit/Pacman#15]
_No sabía cuál era el origen de este problema, pero..._

**Comment by Autinfit** [comment]
_Si quería mover los fantasmas del juego y que el personaje (Pacman) pueda realmente recoger las monedas, me percaté que fue problema de indentación de código, que ya fue solucionado en su momento._

**Comment by MARSFOREVER472** [comment]
_Así es, yo como afiliado del proyecto, como parte de esta empresa, debería arreglar completamente la indentación en varios "if" 's del código ya creado, para que pueda encajar con varios métodos de una clase del formulario._
